name: Lint OpenAPI Descriptions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint OpenAPI spec (Spectral)
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'docs/api-specification.yaml'